Repository Group-5-Project-3/Backend, pull requests merged in 2024-11, with the labels that each got.

#2 Add `PlacesController` for Google Maps API Integration
  Dockerfile
  Makefile
  docker-compose.yml
  src/main/java/com/project3/project3/controller/AuthController.java
  src/main/java/com/project3/project3/controller/PlacesController.java
  src/main/java/com/project3/project3/security/JwtRequestFilter.java
  src/main/java/com/project3/project3/security/WebConfig.java
  src/main/java/com/project3/project3/service/JwtService.java
Labels: enhancement, backend, API, feature

#33 Update User Model
  src/main/java/com/project3/project3/model/User.java
Labels: backend, API, Add Functionality

#32 Add Review Model
  src/main/java/com/project3/project3/model/Review.java
Labels: backend, API, Add Functionality

#31 Add CheckIn Model
  src/main/java/com/project3/project3/model/CheckIn.java
Labels: backend, API, Add Functionality

#30 Add UserBadge Model
  src/main/java/com/project3/project3/model/UserBadge.java
Labels: backend, API, Add Functionality

#29 Add Badge Model and BadgeType Enum
  src/main/java/com/project3/project3/model/Badge.java
  src/main/java/com/project3/project3/model/BadgeType.java
Labels: backend, API, Add Functionality

#28 Add FavoriteTrail Model
  src/main/java/com/project3/project3/model/FavoriteTrail.java
Labels: backend, API, Add Functionality

#27 Add TrailImage Model
  src/main/java/com/project3/project3/model/TrailImage.java
Labels: backend, API, Add Functionality

#26 Add Trail Model
  src/main/java/com/project3/project3/model/Trail.java
Labels: backend, API, Add Functionality

#35 Add Service Classes for Data Models and repositories
  src/main/java/com/project3/project3/service/BadgeService.java
  src/main/java/com/project3/project3/service/CheckInService.java
  src/main/java/com/project3/project3/service/FavoriteTrailService.java
  src/main/java/com/project3/project3/service/ReviewService.java
  src/main/java/com/project3/project3/service/TrailImageService.java
  src/main/java/com/project3/project3/service/TrailService.java
  src/main/java/com/project3/project3/service/UserBadgeService.java
  src/main/java/com/project3/project3/service/UserService.java
Labels: backend, API, Add Functionality

#34 Add Repository Interfaces for Data Models
  src/main/java/com/project3/project3/repository/BadgeRepository.java
  src/main/java/com/project3/project3/repository/CheckInRepository.java
  src/main/java/com/project3/project3/repository/FavoriteTrailRepository.java
  src/main/java/com/project3/project3/repository/ReviewRepository.java
  src/main/java/com/project3/project3/repository/TrailImageRepository.java
  src/main/java/com/project3/project3/repository/TrailRepository.java
  src/main/java/com/project3/project3/repository/UserBadgeRepository.java
  src/main/java/com/project3/project3/repository/UserRepository.java
Labels: backend, API, Add Functionality

#52 Integrate S3 Storage for Image Uploads and Add Image Upload Endpoints
  pom.xml
  src/main/java/com/project3/project3/config/S3Config.java
  src/main/java/com/project3/project3/controller/TrailImageController.java
  src/main/java/com/project3/project3/controller/UserController.java
  src/main/java/com/project3/project3/service/ImageService.java
  src/main/java/com/project3/project3/service/TrailImageService.java
  src/main/java/com/project3/project3/service/UserService.java
Labels: backend, API, Add Functionality

#59 Add Hike Management with HikeController, HikeService, and Related Changes
  src/main/java/com/project3/project3/controller/HikeController.java
  src/main/java/com/project3/project3/model/Badge.java
  src/main/java/com/project3/project3/model/BadgeType.java
  src/main/java/com/project3/project3/model/CheckIn.java
  src/main/java/com/project3/project3/model/FavoriteTrail.java
  src/main/java/com/project3/project3/model/Hike.java
  src/main/java/com/project3/project3/model/User.java
  src/main/java/com/project3/project3/model/UserBadge.java
  src/main/java/com/project3/project3/repository/CheckInRepository.java
  src/main/java/com/project3/project3/repository/FavoriteTrailRepository.java
  src/main/java/com/project3/project3/repository/HikeRepository.java
  src/main/java/com/project3/project3/repository/TrailImageRepository.java
  src/main/java/com/project3/project3/repository/UserBadgeRepository.java
  src/main/java/com/project3/project3/repository/UserRepository.java
  src/main/java/com/project3/project3/service/HikeService.java
  src/main/java/com/project3/project3/service/UserService.java
  src/main/java/com/project3/project3/utility/TimeStamp.java
Labels: backend, API, Add Functionality

#70 Milestones Model, Repository, Service, and Assets for Achievement Tracking
  src/main/java/com/project3/project3/model/Milestones.java
  src/main/java/com/project3/project3/repository/MilestonesRepository.java
  src/main/java/com/project3/project3/service/MilestonesService.java
  src/main/java/com/project3/project3/utility/BadgeObserver.java
  src/main/java/com/project3/project3/utility/Polyline.java
  src/main/resources/assets/Distance/1000km.webp
  src/main/resources/assets/Distance/100km.webp
  src/main/resources/assets/Distance/10km.webp
  src/main/resources/assets/Distance/150km.webp
  src/main/resources/assets/Distance/1km.webp
  src/main/resources/assets/Distance/200km.webp
  src/main/resources/assets/Distance/25km.webp
  src/main/resources/assets/Distance/300km.webp
  src/main/resources/assets/Distance/500km.webp
  src/main/resources/assets/Distance/50km.webp
  src/main/resources/assets/Distance/5km.webp
  src/main/resources/assets/Distance/75km.webp
  src/main/resources/assets/Elevation/100000m.webp
  src/main/resources/assets/Elevation/10000m.webp
  src/main/resources/assets/Elevation/1000m.webp
  src/main/resources/assets/Elevation/100m.webp
  src/main/resources/assets/Elevation/15000m.webp
  src/main/resources/assets/Elevation/20000m.webp
  src/main/resources/assets/Elevation/2000m.webp
  src/main/resources/assets/Elevation/25000m.webp
  src/main/resources/assets/Elevation/50000m.webp
  src/main/resources/assets/Elevation/5000m.webp
  src/main/resources/assets/Elevation/500m.webp
  src/main/resources/assets/Elevation/75000m.webp
  src/main/resources/assets/NationalParks/CA/ChannelIslands.webp
  src/main/resources/assets/NationalParks/CA/DeathValley.webp
  src/main/resources/assets/NationalParks/CA/JoshuaTree.webp
  src/main/resources/assets/NationalParks/CA/Lasso.webp
  src/main/resources/assets/NationalParks/CA/Pinnacles.webp
  src/main/resources/assets/NationalParks/CA/Redwood.webp
  src/main/resources/assets/NationalParks/CA/Sequoia.webp
  src/main/resources/assets/NationalParks/CA/Yosmite.webp
  src/main/resources/assets/TotalHikes/1000hike.webp
  src/main/resources/assets/TotalHikes/100hike.webp
  src/main/resources/assets/TotalHikes/10hike.webp
  src/main/resources/assets/TotalHikes/150hike.webp
  src/main/resources/assets/TotalHikes/1hike.webp
  src/main/resources/assets/TotalHikes/200hike.webp
  src/main/resources/assets/TotalHikes/25hike.webp
  src/main/resources/assets/TotalHikes/300hike.webp
  src/main/resources/assets/TotalHikes/50hike.webp
  src/main/resources/assets/TotalHikes/750hike.webp
  src/main/resources/assets/TotalHikes/75hike.webp
Labels: backend, API, Add Functionality

#69 Feature auth controller tests
  .gitignore
  pom.xml
  src/main/java/com/project3/project3/Project3Application.java
  src/main/java/com/project3/project3/config/S3Config.java
  src/main/java/com/project3/project3/controller/AdminController.java
  src/main/java/com/project3/project3/controller/AuthController.java
  src/main/java/com/project3/project3/model/User.java
  src/main/java/com/project3/project3/security/SecurityConfig.java
  src/main/java/com/project3/project3/security/TestSecurityConfig.java
  src/main/java/com/project3/project3/service/JwtService.java
  src/main/resources/application.properties
  src/test/java/com/project3/project3/controller/AdminControllerTest.java
  src/test/java/com/project3/project3/controller/AuthControllerTest.java
Labels: enhancement, testing, authentication

#67 Add Admin and Security Tests with Configuration Improvements
  pom.xml
  src/main/java/com/project3/project3/Project3Application.java
  src/main/java/com/project3/project3/config/S3Config.java
  src/main/java/com/project3/project3/controller/AdminController.java
  src/main/java/com/project3/project3/model/User.java
  src/main/java/com/project3/project3/security/SecurityConfig.java
  src/main/java/com/project3/project3/security/TestSecurityConfig.java
  src/main/java/com/project3/project3/service/JwtService.java
  src/main/resources/application.properties
  src/test/java/com/project3/project3/controller/AdminControllerTest.java
Labels: enhancement, testing, security, compliance

#78 Add Unit Tests for FavoriteTrailController and HikeController
  src/test/java/com/project3/project3/controller/FavoriteTrailControllerTest.java
  src/test/java/com/project3/project3/controller/HikeControllerTest.java
Labels: enhancement, backend, testing

#79 Add Unit Tests for ReviewController and TrailController
  src/test/java/com/project3/project3/controller/ReviewControllerTest.java
  src/test/java/com/project3/project3/controller/TrailControllerTest.java
Labels: enhancement, backend, testing

#110 Pull Request: S3 Integration and Logging Enhancements
  pom.xml
  src/main/java/com/project3/project3/config/S3Config.java
  src/main/java/com/project3/project3/controller/AdminController.java
  src/main/java/com/project3/project3/controller/AuthController.java
  src/main/java/com/project3/project3/controller/BadgeController.java
  src/main/java/com/project3/project3/controller/FavoriteTrailController.java
  src/main/java/com/project3/project3/controller/HikeController.java
  src/main/java/com/project3/project3/controller/MilestonesController.java
  src/main/java/com/project3/project3/controller/RootController.java
  src/main/java/com/project3/project3/controller/TrailImageController.java
  src/main/java/com/project3/project3/controller/UserBadgeController.java
  src/main/java/com/project3/project3/controller/UserController.java
  src/main/java/com/project3/project3/model/Badge.java
  src/main/java/com/project3/project3/model/FavoriteTrail.java
  src/main/java/com/project3/project3/model/FavoriteTrailWithImagesDTO.java
  src/main/java/com/project3/project3/repository/BadgeRepository.java
  src/main/java/com/project3/project3/repository/CheckInRepository.java
  src/main/java/com/project3/project3/repository/FavoriteTrailRepository.java
  src/main/java/com/project3/project3/repository/HikeRepository.java
  src/main/java/com/project3/project3/service/BadgeService.java
  src/main/java/com/project3/project3/service/CheckInService.java
  src/main/java/com/project3/project3/service/FavoriteTrailService.java
  src/main/java/com/project3/project3/service/ImageService.java
  src/main/java/com/project3/project3/service/TrailImageService.java
  src/main/java/com/project3/project3/service/UserBadgeService.java
  src/main/java/com/project3/project3/service/UserService.java
  src/main/java/com/project3/project3/utility/BadgeInitializer.java
  src/main/java/com/project3/project3/utility/BadgeUtility.java
  src/main/java/com/project3/project3/utility/DefaultImageUtil.java
  src/main/java/com/project3/project3/utility/S3Util.java
  src/main/resources/application.properties
Labels: backend, API, Add Functionality

#98 Added unit tests for AdminController
  src/test/java/com/project3/project3/controller/AdminControllerTest.java
Labels: enhancement, testing
